{% set name = "pyinaturalist-convert" %}
{% set version = "0.6.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0b968276e764a07509bebb68a2eef37821b4b9697e5475de02836dd53996b6ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - poetry >=1.2,<1.4
    - pip
  run:
    - python >={{ python_min }}
    - flatten-dict >=0.4
    - gpxpy >=1.4.2
    - openpyxl >=2.6
    - pandas >=1.2
    - pyarrow >=11.0
    - pyinaturalist >=0.18
    - pytables >=3.6
    - requests-cache >=1.0
    - sqlalchemy >=2.0
    - tablib >=3.0
    - tabulate >=0.8
    - xmltodict >=0.12

test:
  imports:
    - pyinaturalist_convert
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyinat/pyinaturalist-convert
  summary: Convert iNaturalist observation data to and from multiple formats
  license: MIT
  license_file: LICENSE
  doc_url: https://pyinaturalist.readthedocs.io
  dev_url: https://github.com/pyinat/pyinaturalist-convert


extra:
  recipe-maintainers:
    - jwcook
