{% set name = "pyinaturalist-convert" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4ce4380989e49ee5613dfd334c492288e11c96a9053068a4dfb478fc917f468

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - poetry
    - pip
  run:
    - python >=3.8
    - flatten-dict >=0.4
    - gpxpy >=1.4.2
    - openpyxl >=2.6
    - pandas >=1.2
    - pyarrow >=4.0
    - pyinaturalist >=0.15
    - pytables >=3.6
    - python-dwca-reader >=0.15
    - requests-cache =0.7.4
    - tablib >=3.0
    - tabulate >=0.8
    - xmltodict >=0.12

test:
  imports:
    - pyinaturalist_convert
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/JWCook/pyinaturalist-convert
  summary: Convert iNaturalist observation data to and from multiple formats
  license: MIT
  license_file: LICENSE
  doc_url: https://pyinaturalist.readthedocs.io
  dev_url: https://github.com/JWCook/pyinaturalist-convert


extra:
  recipe-maintainers:
    - jwcook
