{% set name = "pyinaturalist-convert" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ced5c3dace17c2f2229e6d2a4c814f9bdf77a8bb111fce7d605af28e7b0be3f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - poetry
    - pip
  run:
    - python >=3.8
    - flatten-dict >=0.4
    - gpxpy >=1.4.2
    - openpyxl >=2.6
    - pandas >=1.2
    - pyarrow >=4.0
    - pyinaturalist >=0.16
    - pytables >=3.6
    - python-dwca-reader >=0.15
    - requests-cache >=0.9.3
    - tablib >=3.0
    - tabulate >=0.8
    - xmltodict >=0.12

test:
  imports:
    - pyinaturalist_convert
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/JWCook/pyinaturalist-convert
  summary: Convert iNaturalist observation data to and from multiple formats
  license: MIT
  license_file: LICENSE
  doc_url: https://pyinaturalist.readthedocs.io
  dev_url: https://github.com/JWCook/pyinaturalist-convert


extra:
  recipe-maintainers:
    - jwcook
